#!/usr/bin/env python3
"""Build the filter's word and name statistics from open corpora (dev-time only).

Nothing here runs in the app, and nothing is downloaded by the app: this script reads source
files that a developer downloaded by hand into a folder, and writes compact data files into
crates/dv-privacy/data/. Sources and licenses are listed in crates/dv-privacy/data/SOURCES.md.

    python3 scripts/build_lexicons.py <source-dir>

<source-dir> must contain:
  he_full.txt                      FrequencyWords 2018, Hebrew (OpenSubtitles), "word count" lines
  iahltwiki-{train,dev,test}.conllu   UD_Hebrew-IAHLTwiki
  knesset-{train,dev,test}.conllu     UD_Hebrew-IAHLTknesset

Output:
  words-N.tsv    normalized Hebrew form <TAB> frequency bucket (1 + floor(log2(count))), sorted,
                 split into files under 1 MB (the repository's file-size limit). The treebanks
                 add written (non-subtitle) forms that the frequency list lacks.
"""

import math
import re
import sys
from collections import Counter
from pathlib import Path

FINALS = str.maketrans({"ך": "כ", "ם": "מ", "ן": "נ", "ף": "פ", "ץ": "צ",
                        "׳": "'", "’": "'", "‘": "'", "`": "'",
                        "״": '"', "“": '"', "”": '"'})
MARKS = re.compile("[֑-ׇֽֿׁׂׅׄ‎‏‍‌﻿]")
HEBREW_WORD = re.compile(r"[א-ת][א-ת'\"]*")

MIN_COUNT = 5
SHARD_BYTES = 900_000


def normalize(word: str) -> str:
    """Same as dv_privacy::text::normalize for a single word."""
    return MARKS.sub("", word).translate(FINALS).lower().strip()


def bucket(count: int) -> int:
    return 1 + int(math.log2(max(count, 1)))


def read_frequency(path: Path) -> Counter:
    freq = Counter()
    with path.open(encoding="utf-8") as f:
        for line in f:
            word, _, count = line.rstrip("\n").rpartition(" ")
            if not word or not count.isdigit():
                continue
            norm = normalize(word)
            if HEBREW_WORD.fullmatch(norm):
                freq[norm] += int(count)
    return freq


def read_conllu(path: Path, seen: Counter) -> None:
    with path.open(encoding="utf-8") as f:
        for line in f:
            if not line.strip() or line.startswith("#"):
                continue
            cols = line.rstrip("\n").split("\t")
            if len(cols) < 10 or "-" in cols[0] or "." in cols[0]:
                continue
            form = normalize(cols[1])
            if HEBREW_WORD.fullmatch(form):
                seen[form] += 1


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    src = Path(sys.argv[1])
    out = Path(__file__).resolve().parent.parent / "crates/dv-privacy/data"

    freq = read_frequency(src / "he_full.txt")
    seen = Counter()
    for corpus in ("iahltwiki", "knesset"):
        for part in ("train", "dev", "test"):
            read_conllu(src / f"{corpus}-{part}.conllu", seen)

    words = {w: c for w, c in freq.items() if c >= MIN_COUNT}
    for w, c in seen.items():
        words[w] = words.get(w, 0) + c
    for old in out.glob("words-*.tsv"):
        old.unlink()
    header = ("# Hebrew word forms and how common they are: 1 + floor(log2(count)).\n"
              "# Generated by scripts/build_lexicons.py; see SOURCES.md. Do not edit by hand.\n")
    shard, size, lines = 1, 0, []
    def flush():
        (out / f"words-{shard}.tsv").write_text(header + "".join(lines), encoding="utf-8")
    for w in sorted(words):
        line = f"{w}\t{bucket(words[w])}\n"
        if size + len(line.encode()) > SHARD_BYTES:
            flush()
            shard, size, lines = shard + 1, 0, []
        lines.append(line)
        size += len(line.encode())
    flush()

    print(f"words-1..{shard}.tsv: {len(words)} forms")
    return 0


if __name__ == "__main__":
    sys.exit(main())
